name: Trigger Reusable Deploy to S3 from Repo1

on:
  push:
    branches:
      - main

jobs:
  trigger-deploy:
    uses: Mohdabounasar012/reusable_repo/.github/workflows/s3.yml@main
    with:
      source_dir: './dist'  # Directory to deploy
      bucket_name: reusable-s3-bucket  # Bucket name

    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}  # Pass AWS_REGION secrets
