# github/workflows/trigger-repo1-s3-deploy.yml
name: Trigger Reusable Deploy to S3 from Repo1

on:
  push:
    branches:
      - main  # Trigger this when code is pushed to the main branch

jobs:
  trigger-deploy:
    uses: Mohdabounasar012/reusable_repo/blob/main/.github/workflows/s3.yml@main  # Replace 'owner' with your GitHub username

    with:
      bucket_name: reusable-s3-bucket
      region: eu-north-1
      source_dir: ./dist  # Replace with the path in your repo to deploy (e.g., 'dist', 'build', etc.)
