# .github/workflows/trigger-repo1-s3-deploy.yml
name: Trigger Reusable Deploy to S3 from Repo1

on:
  push:
    branches:
      - main  # Trigger this when code is pushed to the main branch

jobs:
  trigger-deploy:
    uses: Mohdabounasar012/reusable_repo/.github/workflows/s3.yml@main  # Correct format for referencing the reusable workflow

    with:
      bucket_name: ${{ secrets.S3_BUCKET_NAME }}  # The name of the S3 bucket to deploy to
      region: ${{ secrets.AWS_REGION }}           # The AWS region of the S3 bucket
      source_dir: './dist'                        # The path to the folder to deploy (e.g., 'dist', 'build', etc.)

    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}  # AWS access key
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  # AWS secret access key
